### ISSUE TITLE
Support for Open API spec 

### ISSUE THREAD

**Issue by vishwanathsukumardh** [m-radzikowski/aws-swaggerui#3]
Looks like we need to define the endpoints in the serverless.yml. 
Is there a way to load the endpoints from the Open API spec file?

**Comment by m-radzikowski** [comment]
The `generateConfigFile.js` script, run by the Serverless Framework, [gets the API Gateway ID](https://github.com/m-radzikowski/aws-swaggerui/blob/master/generateConfigFile.js#L36-L39) and saves it in a config file read later by the frontend app.

The frontend app reads this config file and [makes an AWS SDK call](https://github.com/m-radzikowski/aws-swaggerui/blob/master/src/swagger.ts#L23-L28) to get the OpenAPI spec file from the API Gateway.

So the Open API is, in fact, already used. If you want to use other Open API specs you would have to modify the function linked above that loads it in the frontend.
